version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env

