version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app/app
    # environment:
    #   - OPENAI_API_KEY=sk-proj-...  # Remplacez par votre clé réelle
